apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: argo1-get-osm-parts-wft
  namespace: {{ .Values.namespace }}
spec:
  entrypoint: import-osm
  artifactRepositoryRef:
    configMap: cosmogony-artifact-repository
    key: minio
  templates:
  - name: import-osm
    steps:
    - - name: get-osm-data
        template: download-data
  - name: download-data
    volumes:
    - name: sources-vol
      configMap:
        name: osm-sources
    script:
      image: minio/mc:latest
      command: ["/bin/sh"]
      volumeMounts:
        - mountPath: /mnt/osm-sources
          name: sources-vol
      source: |
        echo "--== Start of the collection ==--"
        cd /
        /usr/bin/mc config host add myminio {{ .Values.minio.host }} {{ .Values.minio.accessKey }} {{ .Values.minio.secretKey }}
        for myfile in $(cat /mnt/osm-sources/step1-osm-dl)
        do
          filename="${myfile##*/}"
          echo $filename;
          wget --tries=5 $myfile
          mc cp $filename myminio{{ .Values.minio.cosmogonyPath }}/osm/$filename
        done;
        echo "Finished"

