apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: argo4-db-import-wft
  namespace: {{ .Values.namespace }}
spec:
  entrypoint: get-cosmo
  artifactRepositoryRef:
    configMap: cosmogony-artifact-repository
    key: minio
  templates:
  - name: get-cosmo
    steps:
    - - name: getcosmo
        template: getcosmo
    - - name: cosmogony-import
        template: import-cosmogony
        arguments:
          artifacts:
          - name: cosmogony-source
            from: "{{ "{{" }}steps.getcosmo.outputs.artifacts.cosmogony-output{{ "}}" }}"
    - - name: db-publish
        template: publish-cosmogony
  - name: getcosmo
    script:
      image: minio/mc:latest
      command: ["/bin/sh"]
      source: |
        echo "start of script"
        /usr/bin/mc config host add myminio {{ .Values.minio.host }} {{ .Values.minio.accessKey }} {{ .Values.minio.secretKey }}
        cd /
        mc cp myminio{{ .Values.minio.cosmogonyPath }}/cosmogony-data/concat/cosmogony.jsonl.gz cosmogony.jsonl.gz
        echo "Finished"
    outputs:
      artifacts:
      - name: cosmogony-output
        path: /cosmogony.jsonl.gz
  - name: import-cosmogony
    inputs:
      artifacts:
      - name: cosmogony-source
        path: /mnt/data/cosmogony.jsonl.gz
    container:
      image: {{ .Values.cosmogony_explorer_importer.image.repository }}
      imagePullPolicy: {{ .Values.cosmogony_explorer_importer.image.imagePullPolicy }}
      command: ["python"]
      args: ["import.py", "import-data", "/mnt/data/cosmogony.jsonl.gz", "true"]
      env:
      - name: POSTGRES_HOST
        value: {{ .Values.postgres.host }}
      - name: POSTGRES_PORT
        value: {{ .Values.postgres.port }}
      - name: POSTGRES_DB
        value: {{ .Values.postgres.db }}
      - name: POSTGRES_USER
        value: {{ .Values.postgres.user }}
      - name: POSTGRES_PASSWORD
        value: {{ .Values.postgres.password }}
  - name: publish-cosmogony
    container:
      image: {{ .Values.cosmogony_explorer_importer.image.repository }}
      imagePullPolicy: {{ .Values.cosmogony_explorer_importer.image.imagePullPolicy }}
      command: ["python"]
      args: ["import.py", "publish"]
      env:
      - name: POSTGRES_HOST
        value: {{ .Values.postgres.host }}
      - name: POSTGRES_PORT
        value: {{ .Values.postgres.port }}
      - name: POSTGRES_DB
        value: {{ .Values.postgres.db }}
      - name: POSTGRES_USER
        value: {{ .Values.postgres.user }}
      - name: POSTGRES_PASSWORD
        value: {{ .Values.postgres.password }}
