apiVersion: v1
kind: Secret
metadata:
  labels:
    app: minio
  name: my-minio-cred
  namespace: {{ .Values.namespace }}
stringData:
  accesskey: {{ .Values.minio.accessKey }}
  secretkey: {{ .Values.minio.secretKey }}
type: Opaque
