apiVersion: v1
kind: ConfigMap
metadata:
  name: cosmogony-artifact-repository
  namespace: {{ .Values.namespace }}
  annotations:
    workflows.argoproj.io/default-artifact-repository: minio
data:
  minio: |
    s3:
      bucket: {{ .Values.minio.artifactsPath }}
      endpoint: {{ .Values.minio.endpoint }}
      insecure: true
      accessKeySecret:
        name: my-minio-cred
        key: accesskey
      secretKeySecret:
        name: my-minio-cred
        key: secretkey
