apiVersion: v1
kind: PersistentVolume
metadata:
  name: cosmogony-pv
  namespace: default
  labels:
    type: local
    app: cosmogony
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.persistantVolumes.stats }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cosmogony-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: cosmogony
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      app: cosmogony
  resources:
    requests:
        storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: trex-pv
  namespace: default
  labels:
    type: local
    app: cosmogony-trex
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.persistantVolumes.tilesCache }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: trex-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: cosmogony
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      app: cosmogony-trex
  resources:
    requests:
        storage: 1Gi

