# Default values for cosmo_chart.

cosmogony:
  image:
    repository: osmwithoutborders/cosmogony
    pullPolicy: IfNotPresent
cosmogony_explorer_importer:
  image:
    repository: my-local-registry.url/namespace/cosmogony_explorer_importer
    pullPolicy: Always
cosmogony_explorer_tiles:
  image:
    repository: my-local-registry.url/namespace/cosmogony_explorer_tiles
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
cosmogony_explorer_web:
  image:
    repository: my-local-registry.url/namespace/cosmogony_explorer_web
    pullPolicy: Always
  service:
    type: ClusterIP
cosmogony_explorer_api:
  image:
    repository: my-local-registry.url/namespace/cosmogony_explorer_api
    pullPolicy: Always
  service:
    type: ClusterIP

namespace: cosmogony

persistantVolumes:
  stats: /var/data/cosmogony/stats
  tilesCache: /var/data/cosmogony/trex

minio:
  host: http://minio.default.svc.cluster.local:9000
  accessKey: minioaccess
  secretKey: miniosecret
  cosmogonyPath: /cosmogony

postgres:
  host: postgres-postgresql.default
  post: 5432
  user: cosmogony
  password: cosmogony
  db: cosmogony

ingress:
  enabled: false
  class: nginx
  hosts:
    - host: cosmogony.local
      serviceName: cosmogony-web
      servicePort: 80

nodeSelector: {}


