# Default values for cosmo_chart.

cosmogony:
  image:
    repository: osmwithoutborders/cosmogony
    pullPolicy: IfNotPresent
cosmogony_explorer_importer:
  image:
    repository: my-local-registry.url/namespace/cosmogony_explorer_importer
    pullPolicy: Always
cosmogony_explorer_tiles:
  image:
    repository: my-local-registry.url/namespace/cosmogony_explorer_tiles
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
cosmogony_explorer_web:
  image:
    repository: my-local-registry.url/namespace/cosmogony_explorer_web
    pullPolicy: Always
  service:
    type: ClusterIP
cosmogony_explorer_api:
  image:
    repository: my-local-registry.url/namespace/cosmogony_explorer_api
    pullPolicy: Always
  service:
    type: ClusterIP

namespace: cosmogony

osmSources:
  - "http://download.geofabrik.de/europe-latest.osm.pbf"
  - "http://download.geofabrik.de/africa-latest.osm.pbf"
  - "http://download.geofabrik.de/antarctica-latest.osm.pbf"
  - "http://download.geofabrik.de/asia-latest.osm.pbf"
  - "http://download.geofabrik.de/australia-oceania-latest.osm.pbf"
  - "http://download.geofabrik.de/central-america-latest.osm.pbf"
  - "http://download.geofabrik.de/north-america-latest.osm.pbf"
  - "http://download.geofabrik.de/south-america-latest.osm.pbf"

persistantVolumes:
  stats: /var/data/cosmogony/stats
  tilesCache: /var/data/cosmogony/trex

minio:
  endpoint: minio.default.svc.cluster.local:9000
  scheme: http
  accessKey: minioaccess
  secretKey: miniosecret
  cosmogonyPath: cosmogony # be carefull not to include the `/` first character
  artifactsPath: artifacts

postgres:
  host: postgres-postgresql.default
  post: 5432
  user: cosmogony
  password: cosmogony
  db: cosmogony

ingress:
  enabled: false
  class: nginx
  hosts:
    - host: "cosmogony.local"
      paths:
        - path: "/"
          serviceName: cosmogony-web
          servicePort: 80


