apiVersion: v1
kind: ConfigMap
metadata:
  name: cosmogony-artifact-repository
  namespace: cosmogony
data:
  minio: |
    s3:
      bucket: my-bucket
      endpoint: minio.argo.svc.cluster.local:9000
      insecure: true
      accessKeySecret:
        name: my-minio-cred
        key: accesskey
      secretKeySecret:
        name: my-minio-cred
        key: secretkey
