apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cosmogony
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Access-Control-Allow-Origin: *";
spec:
  rules:
  - host: {{ .Values.ingress.hosts.host }}
    http:
      paths:
      - backend:
          serviceName: cosmogony-web
          servicePort: 80
        path: /
