apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosmogony-web
  namespace: {{ .Values.namespace }}
  labels:
    app: cosmogony-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cosmogony-web
  template:
    metadata:
      labels:
        app: cosmogony-web
    spec:
      containers:
      - name: cosmogony-web
        image: {{ .Values.cosmogony_explorer_web.image.repository }}
        imagePullPolicy: {{ .Values.cosmogony_explorer_web.image.pullPolicy}}
        volumeMounts:
          - mountPath: /mnt/data_dashboard
            name: cosmov
      volumes:
        - name: cosmov
          persistentVolumeClaim:
            claimName: cosmogony-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: cosmogony-web
  namespace: {{ .Values.namespace }}
  labels:
    app: cosmogony-web
spec:
  type: {{ .Values.cosmogony_explorer_tiles.service.type }}
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: cosmogony-web
