apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosmogony-api
  namespace: {{ .Values.namespace }}
  labels:
    app: cosmogony-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cosmogony-api
  template:
    metadata:
      labels:
        app: cosmogony-api
    spec:
      containers:
      - name: cosmogony-api
        image: {{ .Values.cosmogony_explorer_api.image.repository }}
        imagePullPolicy: {{ .Values.cosmogony_explorer_api.image.pullPolicy}}
        env:
        - name: POSTGRES_HOST
          value: {{ .Values.postgres.host }}
        - name: POSTGRES_PORT
          value: {{ .Values.postgres.port }}
        - name: POSTGRES_DB
          value: {{ .Values.postgres.db }}
        - name: POSTGRES_USER
          value: {{ .Values.postgres.user }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres.password }}
---
apiVersion: v1
kind: Service
metadata:
  name: cosmogony-api
  namespace: {{ .Values.namespace }}
  labels:
    app: cosmogony-api
spec:
  type: {{ .Values.cosmogony_explorer_tiles.service.type }}
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: cosmogony-api
